# Generated by Django 5.0.4 on 2024-05-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=9000000, upload_to='files/')),
                ('content', models.TextField(blank=True, max_length=9000000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, max_length=9000000)),
            ],
        ),
        migrations.CreateModel(
            name='PositionalIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=9000000)),
                ('doc_id', models.CharField(max_length=9000000)),
                ('positions', models.TextField(max_length=9000000)),
            ],
        ),
        migrations.CreateModel(
            name='IndexedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=9000000)),
                ('positions', models.TextField(max_length=9000000)),
                ('document', models.ForeignKey(max_length=9000000, on_delete=django.db.models.deletion.CASCADE, to='documents_search.document')),
            ],
        ),
    ]
