# Generated by Django 5.0.4 on 2024-05-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionalindex',
            name='raw_text',
            field=models.TextField(blank=True, default='', max_length=9000000),
        ),
    ]
